//! SeaORM Entity. Generated by sea-orm-codegen 0.8.0

use super::sea_orm_active_enums::ReportSendType;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "log_report")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub cron: String,
    pub interval: Option<i32>,
    pub query: String,
    #[sea_orm(unique)]
    pub name: String,
    pub index: Option<Uuid>,
    pub send_type: Option<ReportSendType>,
    pub send_to: Option<String>,
    pub columns: Option<Json>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::log_index::Entity",
        from = "Column::Index",
        to = "super::log_index::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    LogIndex,
}

impl Related<super::log_index::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LogIndex.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
