//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.4

pub mod prelude;

pub mod log_accesses;
pub mod log_admin_ticks;
pub mod log_admin_user;
pub mod log_index;
pub mod log_log;
pub mod log_report;
pub mod log_structs;
pub mod sea_orm_active_enums;
