//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.2

pub use super::log_accesses::Entity as LogAccesses;
pub use super::log_admin_ticks::Entity as LogAdminTicks;
pub use super::log_admin_user::Entity as LogAdminUser;
pub use super::log_index::Entity as LogIndex;
pub use super::log_log::Entity as LogLog;
pub use super::log_report::Entity as LogReport;
pub use super::log_structs::Entity as LogStructs;
