//! SeaORM Entity. Generated by sea-orm-codegen 0.8.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "report_send_type")]
pub enum ReportSendType {
    #[sea_orm(string_value = "email")]
    Email,
    #[sea_orm(string_value = "file")]
    File,
}
