// @generated by protobuf-ts 2.8.2 with parameter optimize_code_size
// @generated from protobuf file "proto/admin.proto" (package "admin", syntax proto3)
// tslint:disable
import { IndexSearchResult } from "./index";
import { IndexSearchRequest } from "./index";
import { IndexListResponse } from "./index";
import { IndexListRequest } from "./index";
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message admin.AdminAuth
 */
export interface AdminAuth {
    /**
     * @generated from protobuf field: string token = 1;
     */
    token: string;
}
// @generated message type with reflection information, may provide speed optimized methods
class AdminAuth$Type extends MessageType<AdminAuth> {
    constructor() {
        super("admin.AdminAuth", [
            { no: 1, name: "token", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message admin.AdminAuth
 */
export const AdminAuth = new AdminAuth$Type();
/**
 * @generated ServiceType for protobuf service admin.AdminPanel
 */
export const AdminPanel = new ServiceType("admin.AdminPanel", [
    { name: "GetIndexes", options: {}, I: IndexListRequest, O: IndexListResponse },
    { name: "Search", options: {}, I: IndexSearchRequest, O: IndexSearchResult }
]);
