// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface LogResponse {
  index: string | null;
  timestamp: string;
  data: any;
}
