// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface SearchQuery {
  time_start: string;
  time_end: string | null;
  take: bigint | null;
  skip: bigint | null;
  query: string | null;
}
